service: serverless-boilerplate
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true

custom:
  serverless-offline:
    useChildProcesses: false

functions:
  - ${file(./src/handlers/author/functions.yml)}
