service: serverless-boilerplate
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  # - serverless-bundle
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1

functions:
  - ${file(./src/handlers/author/functions.yml)}
