class ResponseCodes {
  static DATA_CREATED = 'DATA_CREATED';
  static DATA_RETRIEVED = 'DATA_RETRIEVED';
  static LIST_RETRIEVED = 'LIST_RETRIEVED';
  static INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
  static NOT_FOUND = 'NOT_FOUND';
  static DATA_UPDATED = 'DATA_UPDATED';
  static DATA_DELETED = 'DATA_DELETED';
  static BAD_REQUEST = 'BAD_REQUEST';
}

export { ResponseCodes };
